name: asteroid-mining
services:
  db:
    image: postgres:18.1-alpine
    container_name: asteroid-mining-db
    environment:
      POSTGRES_USER: asmuser
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: asteroid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  postgres-data: