spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/asteroid_db"
    username: "asmuser"
    password: "${DB_USER_PASSWORD}"

  logging:
    level:
      org.springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.jdbc.core.StatementCreatorUtils: TRACE