spring:
  application:
    name: asteroid-mining-api

# For SSL encryption we need to generate a keypair and configure the following application properties.
server:
  port: 8443 # we use port 8443 instead 443 to avoid authorization errors
  ssl:
    enabled: true
    # The keystore file is excluded from git for security reasons.
    # To generate it, run the following command in your terminal:
    # keytool -genkeypair -alias asteroidMiningKey -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore src/main/resources/asteroidMining.p12 -validity 3650
    key-store: classpath:asteroidMining.p12
    # For security reasons, the password is not stored in this file.
    # Please set the environment variable SERVER_SSL_KEY_STORE_PASSWORD with the password you provided on the keypair
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: asmSslKey
